// Code generated by protoc-gen-go. DO NOT EDIT.
// source: word.proto

package wordservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type LookupRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{0}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

// The response message containing the greetings
type LookupReply struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupReply) Reset()         { *m = LookupReply{} }
func (m *LookupReply) String() string { return proto.CompactTextString(m) }
func (*LookupReply) ProtoMessage()    {}
func (*LookupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{1}
}

func (m *LookupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupReply.Unmarshal(m, b)
}
func (m *LookupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupReply.Marshal(b, m, deterministic)
}
func (m *LookupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupReply.Merge(m, src)
}
func (m *LookupReply) XXX_Size() int {
	return xxx_messageInfo_LookupReply.Size(m)
}
func (m *LookupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupReply.DiscardUnknown(m)
}

var xxx_messageInfo_LookupReply proto.InternalMessageInfo

func (m *LookupReply) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*LookupRequest)(nil), "wordservice.LookupRequest")
	proto.RegisterType((*LookupReply)(nil), "wordservice.LookupReply")
}

func init() { proto.RegisterFile("word.proto", fileDescriptor_757f6f9a86a352a0) }

var fileDescriptor_757f6f9a86a352a0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xcf, 0x2f, 0x4a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0xb1, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x95, 0x94, 0xb9, 0x78, 0x7d, 0xf2, 0xf3, 0xb3, 0x4b, 0x0b, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x40, 0xf2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x3c, 0x17, 0x37, 0x4c, 0x51, 0x41, 0x4e, 0xa5, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51,
	0x26, 0x54, 0x05, 0x88, 0x69, 0x14, 0xc7, 0xc5, 0x1d, 0x8e, 0x30, 0x54, 0xc8, 0x9f, 0x4b, 0x34,
	0xb4, 0x28, 0x29, 0x31, 0x2f, 0x25, 0x33, 0xb9, 0x24, 0x33, 0x3f, 0x2f, 0xb1, 0xa8, 0x12, 0xa2,
	0x5d, 0x48, 0x4a, 0x0f, 0xc9, 0x6e, 0x3d, 0x14, 0x8b, 0xa5, 0x24, 0xb0, 0xca, 0x15, 0xe4, 0x54,
	0x2a, 0x31, 0x38, 0xf1, 0x46, 0x21, 0x3b, 0x3a, 0x89, 0x0d, 0xec, 0x11, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6f, 0x37, 0x32, 0xe1, 0xd6, 0x00, 0x00, 0x00,
}
